const ITEM = {
    88: require("TFTAssistant/assets/set2/new_item_icons/88.png"),
    77: require("TFTAssistant/assets/set2/new_item_icons/77.png"),
    89: require("TFTAssistant/assets/set2/new_item_icons/89.png"),
    48: require("TFTAssistant/assets/set2/new_item_icons/48.png"),
    49: require("TFTAssistant/assets/set2/new_item_icons/49.png"),
    59: require("TFTAssistant/assets/set2/new_item_icons/59.png"),
    58: require("TFTAssistant/assets/set2/new_item_icons/58.png"),
    99: require("TFTAssistant/assets/set2/new_item_icons/99.png"),
    8: require("TFTAssistant/assets/set2/new_item_icons/8.png"),
    66: require("TFTAssistant/assets/set2/new_item_icons/66.png"),
    67: require("TFTAssistant/assets/set2/new_item_icons/67.png"),
    9: require("TFTAssistant/assets/set2/new_item_icons/9.png"),
    14: require("TFTAssistant/assets/set2/new_item_icons/14.png"),
    28: require("TFTAssistant/assets/set2/new_item_icons/28.png"),
    29: require("TFTAssistant/assets/set2/new_item_icons/29.png"),
    15: require("TFTAssistant/assets/set2/new_item_icons/15.png"),
    17: require("TFTAssistant/assets/set2/new_item_icons/17.png"),
    16: require("TFTAssistant/assets/set2/new_item_icons/16.png"),
    12: require("TFTAssistant/assets/set2/new_item_icons/12.png"),
    13: require("TFTAssistant/assets/set2/new_item_icons/13.png"),
    39: require("TFTAssistant/assets/set2/new_item_icons/39.png"),
    11: require("TFTAssistant/assets/set2/new_item_icons/11.png"),
    38: require("TFTAssistant/assets/set2/new_item_icons/38.png"),
    35: require("TFTAssistant/assets/set2/new_item_icons/35.png"),
    10203: require("TFTAssistant/assets/set2/new_item_icons/10203.png"),
    10202: require("TFTAssistant/assets/set2/new_item_icons/10202.png"),
    34: require("TFTAssistant/assets/set2/new_item_icons/34.png"),
    22: require("TFTAssistant/assets/set2/new_item_icons/22.png"),
    36: require("TFTAssistant/assets/set2/new_item_icons/36.png"),
    10201: require("TFTAssistant/assets/set2/new_item_icons/10201.png"),
    37: require("TFTAssistant/assets/set2/new_item_icons/37.png"),
    23: require("TFTAssistant/assets/set2/new_item_icons/23.png"),
    27: require("TFTAssistant/assets/set2/new_item_icons/27.png"),
    33: require("TFTAssistant/assets/set2/new_item_icons/33.png"),
    10204: require("TFTAssistant/assets/set2/new_item_icons/10204.png"),
    26: require("TFTAssistant/assets/set2/new_item_icons/26.png"),
    18: require("TFTAssistant/assets/set2/new_item_icons/18.png"),
    24: require("TFTAssistant/assets/set2/new_item_icons/24.png"),
    25: require("TFTAssistant/assets/set2/new_item_icons/25.png"),
    19: require("TFTAssistant/assets/set2/new_item_icons/19.png"),
    4: require("TFTAssistant/assets/set2/new_item_icons/4.png"),
    56: require("TFTAssistant/assets/set2/new_item_icons/56.png"),
    5: require("TFTAssistant/assets/set2/new_item_icons/5.png"),
    57: require("TFTAssistant/assets/set2/new_item_icons/57.png"),
    55: require("TFTAssistant/assets/set2/new_item_icons/55.png"),
    7: require("TFTAssistant/assets/set2/new_item_icons/7.png"),
    69: require("TFTAssistant/assets/set2/new_item_icons/69.png"),
    68: require("TFTAssistant/assets/set2/new_item_icons/68.png"),
    6: require("TFTAssistant/assets/set2/new_item_icons/6.png"),
    78: require("TFTAssistant/assets/set2/new_item_icons/78.png"),
    44: require("TFTAssistant/assets/set2/new_item_icons/44.png"),
    2: require("TFTAssistant/assets/set2/new_item_icons/2.png"),
    3: require("TFTAssistant/assets/set2/new_item_icons/3.png"),
    45: require("TFTAssistant/assets/set2/new_item_icons/45.png"),
    1: require("TFTAssistant/assets/set2/new_item_icons/1.png"),
    47: require("TFTAssistant/assets/set2/new_item_icons/47.png"),
    46: require("TFTAssistant/assets/set2/new_item_icons/46.png"),
    
}


export const getItem = (number) => { // dynamically invoked
    return ITEM[number]
}
